<?php

//Disable direct view.
if (!defined('IN_PLUGIN'))
    die('You can not access this file directly.');

?>
<div id="tinyQeWrapper">
    <table id="tinyQEMain">
        <tbody>
            <tr class="emailForm hidden center" id="loader">
                <td colspan="3">
                    <img src="<?php echo ROOT_URL_PATH; ?>/img/ajax-loader.gif" />
                </td>
            </tr>
            <tr class="emailForm hidden" id="messagesReport">
                <td colspan="3">
                    <p></p>
                </td>
            </tr>
            <tr class="emailForm">
                <td class="descTdWidth"><label for="to" class="paddingTop">Receivers:</label></td>
                <td><textarea cols="1" rows="1" class="receiver fullWidth" id="to" name="to"></textarea></td>
                <td class="imgTdWidth">
                    <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array(
                        'class'     => 'Tqe_Ajax_Mail',
                        'action'    => 'list',
                        'fieldType' => Tqe_Helpers::TO_FIELD,
                        'historyId' => retGet('historyId')
                    )); ?>" class="listUsersAction">
                        <img src="<?php echo ROOT_URL_PATH; ?>/img/add_male_user.png" />
                    </a>
                </td>
            </tr>
            <tr class="emailForm hidden" id="ccCopy">
                <td><label for="cc" class="paddingTop">Copy:</label></td>
                <td><textarea cols="1" rows="1" class="receiver fullWidth" id="cc" name="cc"></textarea></td>
                <td>
                	<input type="hidden" id="useCc" name="useCc" value="" />
                    <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array(
                        'class'     => 'Tqe_Ajax_Mail',
                        'action'    => 'list',
                        'fieldType' => Tqe_Helpers::CC_FIELD,
                        'historyId' => retGet('historyId')
                    )); ?>" class="listUsersAction">
                        <img src="<?php echo ROOT_URL_PATH; ?>/img/add_male_user.png" />
                    </a>
                    <a href="" id="remCcLink"><img src="<?php echo ROOT_URL_PATH; ?>/img/remove_male_user.png" /></a>
                </td>
            </tr>
            <tr class="emailForm hidden" id="bccCopy">
                <td><label for="bcc" class="paddingTop">Hidden copy:</label></td>
                <td><textarea cols="1" rows="1" class="receiver fullWidth" id="bcc" name="bcc"></textarea></td>
                <td>
                	<input type="hidden" id="useBcc" name="useBcc" value="" />
                    <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array(
                        'class'     => 'Tqe_Ajax_Mail',
                        'action'    => 'list',
                        'fieldType' => Tqe_Helpers::BCC_FIELD,
                        'historyId' => retGet('historyId')
                    )); ?>" class="listUsersAction">
                        <img src="<?php echo ROOT_URL_PATH; ?>/img/add_male_user.png" />
                    </a>
                    <a href="" id="remBccLink"><img src="<?php echo ROOT_URL_PATH; ?>/img/remove_male_user.png" /></a>
                </td>
            </tr>
            <tr class="emailForm">
                <td colspan="3">
                    <a href="#" id="addCc">Add copy</a><span id="addSep"> | </span>
                    <a href="##" id="addBcc">Add hidden copy</a>
                </td>
            </tr>
            <tr class="emailForm">
                <td class="descTdWidth"><label for="subject" class="paddingTop">Subject:</label></td>
                <td><input type="text" class="fullWidth" name="subject" id="subject" /></td>
                <td class="imgTdWidth">&nbsp;</td>
            </tr>
            <tr class="emailForm">
                <td><label for="message" class="paddingTop">Message:</label></td>
                <td><textarea cols="1" rows="1" class="message fullWidth" id="message" name="message"></textarea></td>
                <td>&nbsp;</td>
            </tr>
            <tr class="emailForm clear">
                <td colspan="3">
                    <p class="submit" style="float: left; padding-left: 0px;">
                        <input type="button" name="newEmail" id="newEmail" value="New" />
                        <input type="button" name="sendMail" id="sendMail" value="Send" />
                        <input type="button" name="saveMail" id="saveMail" value="Save" />
                        <input type="button" name="discardMail" id="discardMail" value="Discard" />
                    </p>
                </td>
            </tr>
        </tbody>
    </table>
    <ul id="izbornik">
        <li><a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array(
                'class'     => 'Tqe_Ajax_Sent',
                'action'    => 'list',
                'historyId' => retGet('historyId')
            )); ?>" id="outbox">Outbox</a> |</li>
        <li><a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array(
                'class'     => 'Tqe_Ajax_Draft',
                'action'    => 'list',
                'historyId' => retGet('historyId')
            )); ?>" id="drafts">Drafts</a> |</li>
        <li><a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array(
                'class'     => 'Tqe_Ajax_Trash',
                'action'    => 'list',
                'historyId' => retGet('historyId')
            )); ?>" id="trash">Trash</a> |</li>
        <li>
            <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array(
                'class'     => 'Tqe_Ajax_Abook',
                'action'    => 'add',
                'historyId' => retGet('historyId')
            )); ?>" id="aBook">Address book
            </a>
        </li>
    </ul>
    <div id="menuHolder">
    </div>
</div>
<script type="text/javascript">
jQuery(document).ready(function()
{
	jQuery.tinyQE.variables.ajaxUrl  = '<?php echo AJAX_URL; ?>';
    jQuery.tinyQE.variables.toField  = '<?php echo Tqe_Helpers::TO_FIELD; ?>';
    jQuery.tinyQE.variables.ccField  = '<?php echo Tqe_Helpers::CC_FIELD; ?>';
    jQuery.tinyQE.variables.bccField = '<?php echo Tqe_Helpers::BCC_FIELD; ?>';
    jQuery.tinyQE.variables.autoSave.delay = <?php echo $this->_data->delay; ?> || jQuery.tinyQE.variables.autoSave.delay;
});
</script>