<?php

//Disable direct view.
if (!defined('IN_PLUGIN'))
    die('You can not access this file directly.');

$template = new Tqe_Template(TQE_TEMPLATES_DIR, $this->_data);

$result = $this->_data->result;

?>
<table>
    <tbody>
        <tr>
            <td class="extendTdWidth">Receivers:</td>
            <td><?php echo htmlentities($result->to); ?></td>
        </tr>
        <?php if ($result->useCc === '1') : ?>
        <tr>
            <td class="extendTdWidth">Copy:</td>
            <td><?php echo htmlentities($result->cc); ?></td>
        </tr>
        <?php endif; ?>
        <?php if ($result->useBcc === '1') : ?>
        <tr>
            <td class="extendTdWidth">Hidden copy:</td>
            <td><?php echo htmlentities($result->bcc); ?></td>
        </tr>
        <?php endif; ?>
        <tr>
            <td class="extendTdWidth">Subject:</td>
            <td><?php echo htmlentities($result->subject); ?></td>
        </tr>
        <tr>
            <td class="extendTdWidth">Message:</td>
            <td><?php echo htmlentities($result->message); ?></td>
        </tr>
        <tr>
            <td class="extendTdWidth">Deleted:</td>
            <td>
                <?php echo date_i18n(Tqe_Config::getWpConfig('date_format'), $result->date); ?>
                in
                <?php echo date_i18n(Tqe_Config::getWpConfig('time_format'), $result->date); ?>
            </td>
        </tr>
    </tbody>
</table>
<div class="alignRight marginTop5">
    <?php $template->assignFile('misc/nav.phtml')->render(); ?>
</div>