<?php

//Disable direct view.
if (!defined('IN_PLUGIN'))
    die('You can not access this file directly.');

?>
<div class="wrap" id="tinyQeWrapper">
    <h3>Tiny Quick E-mail settings</h3>

    <form action="" method="post"
        <table style="width: 500px">
            <tbody>
                <tr class="listTable hidden center" id="loader">
                    <td>
                        <img src="<?php echo ROOT_URL_PATH; ?>/img/ajax-loader.gif" />
                    </td>
                </tr>
                <tr class="listTable hidden" id="messagesReport">
                    <td>
                        <p></p>
                    </td>
                </tr>
            </tbody>
        </table>

        <table class="widefat" style="width: 500px">
            <tbody>
                <tr class="listTable">
                    <td width="50%">Contacts displayed: <sup>1</sup></td>
                    <td class="alignLeft">
                        <select name="displayContacts" id="displayContacts">
                            <?php for($i = 10; $i < 101; $i += 10) : ?>
                            <option value="<?php echo $i; ?>"<?php if ($this->_data->displayContacts === $i) : ?> selected="selected"<?php endif; ?>><?php echo $i; ?></option>
                            <?php endfor; ?>
                        </select>
                    </td>
                </tr>
                <tr class="listTable">
                    <td width="50%">Categories displayed: <sup>2</sup></td>
                    <td class="alignLeft">
                        <select name="displayCategories" id="displayCategories">
                            <?php for($i = 10; $i < 101; $i += 10) : ?>
                            <option value="<?php echo $i; ?>"<?php if ($this->_data->displayCategories === $i) : ?> selected="selected"<?php endif; ?>><?php echo $i; ?></option>
                            <?php endfor; ?>
                        </select>
                    </td>
                </tr>
                <tr class="listTable">
                    <td width="50%">E-mails displayed: <sup>3</sup></td>
                    <td class="alignLeft">
                        <select name="displayEmails" id="displayEmails">
                            <?php for($i = 10; $i < 101; $i += 10) : ?>
                            <option value="<?php echo $i; ?>"<?php if ($this->_data->displayEmails === $i) : ?> selected="selected"<?php endif; ?>><?php echo $i; ?></option>
                            <?php endfor; ?>
                        </select>
                    </td>
                </tr>
                <tr class="listTable">
                    <td width="50%">Auto save delay: <sup>4</sup></td>
                    <td class="alignLeft">
                        <input type="text" name="autoSaveEvery" id="autoSaveEvery" value="<?php echo $this->_data->autoSaveEvery; ?>" class="fullWidth" />
                    </td>
                </tr>
                <tr class="listTable">
                    <td width="50%">Clean trash: <sup>5</sup></td>
                    <td class="alignLeft">
                        <input type="text" name="deleteTrashAfter" id="deleteTrashAfter" value="<?php echo $this->_data->deleteTrashAfter; ?>" class="fullWidth" />
                    </td>
                </tr>
            </tbody>
        </table>

        <p class="submit">
            <input type="button" name="saveSettings" class="button-primary" id="saveSettings" value="Save" />
            <input type="button" name="defaultSettings" id="defaultSettings" value="Default" />
            <input type="reset" value="Reset" />
        </p>
        <p>
            <ol>
                <li>Number of contacts displayed on one page in address book.</li>
                <li>Number of categories displayed on one page in address book.</li>
                <li>Number of e-mails displayed in `Sent`, `Draft` and `Trash` sections.</li>
                <li>Number of seconds before auto save is executed.</li>
                <li>Number of seconds after e-mails in `Trash` are deleted from database.</li>
            </ol>
        </p>
    </form>
</div>
<script type="text/javascript">
jQuery(document).ready(function()
{
    jQuery.tinyQE.variables.ajaxUrl  = '<?php echo AJAX_URL; ?>';
});
</script>