<?php

//Disable direct view.
if (!defined('IN_PLUGIN'))
    die('You can not access this file directly.');

?>
<table>
    <tbody>
        <tr>
            <td class="descTdWidth"><label for="firstName" class="paddingTop">First name:</label></td>
            <td><input type="text" class="fullWidth" id="firstName" name="firstName" /></td>
        </tr>
        <tr>
            <td class="descTdWidth"><label for="middleName" class="paddingTop">Middle name:</label></td>
            <td><input type="text" class="fullWidth" id="middleName" name="middleName" /></td>
        </tr>
        <tr>
            <td class="descTdWidth"><label for="lastName" class="paddingTop">Last name:</label></td>
            <td><input type="text" class="fullWidth" id="lastName" name="lastName" /></td>
        </tr>
        <tr>
            <td class="descTdWidth"><label for="email" class="paddingTop">E-mail:</label></td>
            <td><input type="text" class="fullWidth" id="email" name="email" /></td>
        </tr>
        <tr>
            <td class="descTdWidth"><label for="category" class="paddingTop">Category:</label></td>
            <td>
                <select name="category" id="category">
                    <option value="-1">Select category</option>
                    <?php foreach ($this->_data->cats as $category) : ?>
                    <option value="<?php echo $category->id; ?>"><?php echo $category->name; ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr class="clear">
            <td colspan="2">
                <p class="submit" style="float: left; padding-left: 0px;">
                    <input type="button" name="tqeAddContact" id="tqeAddContact" value="Add contact" />
                </p>
            </td>
        </tr>
    </tbody>
</table>