<?php

//Disable direct view.
if (!defined('IN_PLUGIN'))
    die('You can not access this file directly.');

?>
<table>
    <tbody>
        <tr>
            <td class="extendTdWidth"><label for="categoryName" class="paddingTop">Category name:</label></td>
            <td><input type="text" class="fullWidth" id="categoryName" name="categoryName" /></td>
        </tr>
        <tr class="clear">
            <td colspan="2">
                <p class="submit" style="float: left; padding-left: 0px;">
                    <input type="button" name="addCategoryTqe" id="addCategoryTqe" value="Add category" />
                </p>
            </td>
        </tr>
    </tbody>
</table>