<?php

//Disable direct view.
if (!defined('IN_PLUGIN'))
    die('You can not access this file directly.');

if (isset($this->_data->count) && $this->_data->count < 1) :
?>
<table>
    <tbody>
        <tr>
            <td>
                You do not have any category created. Click <a href="<?php echo AJAX_URL; ?>&class=Tqe_Ajax_Abook&action=addCat" id="tqeAddCategory">here</a> to create one.
            </td>
        </tr>
    </tbody>
</table>
<?php else : ?>
<div class="tablenav">
    <div class="tablenav-pages"><?php echo $this->_data->displaying; ?></div>
</div>
<table class="widefat listTable">
    <thead>
        <tr>
            <th class="check-column"><input type="checkbox" class="tqeSelectAll" /></th>
            <th>
                <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
                    'order'     => 'name',
                    'desc'      => (retGet('order') === 'name' && retGet('desc') !== 'true') ? 'true' : ''
                ))); ?>" class="tqeLink">Name</a>
                <?php if (retGet('order') === 'name') : ?>
                &nbsp;<img src="<?php echo ROOT_URL_PATH; ?>/img/triangle_<?php echo (retGet('desc') === 'true') ? 'down' : 'up'; ?>.png" alt="Order">
                <?php endif; ?>
            </th>
            <th style="width: 80px;">
                <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
                    'order'     => 'count',
                    'desc'      => (retGet('order') === 'count' && retGet('desc') !== 'true') ? 'true' : ''
                ))); ?>" class="tqeLink">Contacts</a>
                <?php if (retGet('order') === 'count') : ?>
                &nbsp;<img src="<?php echo ROOT_URL_PATH; ?>/img/triangle_<?php echo (retGet('desc') === 'true') ? 'down' : 'up'; ?>.png" alt="Order">
                <?php endif; ?>
            </th>
            <th style="width: 100px;" class="alignCenter">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->_data->result as $result) : ?>
        <tr>
            <td><input type="checkbox" class="tqeSelect" value="<?php echo $result->id; ?>" /></td>
            <td><?php echo $result->name; ?></td>
            <td class="alignCenter"><a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
                    'action'    => 'list',
                    'order'     => '',
                    'desc'      => '',
                    'currPage'  => '',
                    'cond'      => array(
                        'category' => $result->id
                    )
                ))); ?>" class="tqeLink"><?php echo $result->count; ?></a></td>
            <td class="alignCenter">
                <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
                    'action' => 'viewCat',
                    'id'     => $result->id
                ))); ?>" class="tqeLink">
                    <img src="<?php echo ROOT_URL_PATH; ?>/img/info.png">
                </a>
                <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
                    'action' => 'editCat',
                    'id'     => $result->id
                ))); ?>" class="tqeLink">
                    <img src="<?php echo ROOT_URL_PATH; ?>/img/edit.png">
                </a>
                <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
                    'action' => 'delCat',
                    'id'     => $result->id
                ))); ?>" class="tqeLink">
                    <img src="<?php echo ROOT_URL_PATH; ?>/img/delete.png">
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <th class="check-column"><input type="checkbox" class="tqeSelectAll" /></th>
            <th>
                <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
                    'order'     => 'name',
                    'desc'      => (retGet('order') === 'name' && retGet('desc') !== 'true') ? 'true' : ''
                ))); ?>" class="tqeLink">Name</a>
                <?php if (retGet('order') === 'name') : ?>
                &nbsp;<img src="<?php echo ROOT_URL_PATH; ?>/img/triangle_<?php echo (retGet('desc') === 'true') ? 'down' : 'up'; ?>.png" alt="Order">
                <?php endif; ?>
            </th>
            <th>
                <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
                    'order'     => 'count',
                    'desc'      => (retGet('order') === 'count' && retGet('desc') !== 'true') ? 'true' : ''
                ))); ?>" class="tqeLink">Contacts</a>
                <?php if (retGet('order') === 'count') : ?>
                &nbsp;<img src="<?php echo ROOT_URL_PATH; ?>/img/triangle_<?php echo (retGet('desc') === 'true') ? 'down' : 'up'; ?>.png" alt="Order">
                <?php endif; ?>
            </th>
            <th class="alignCenter">Actions</th>
        </tr>
    </tfoot>
</table>
<?php if ($this->_data->pagin) : ?>
<div id="tqePagin" class="tablenav">
    <div class="tablenav-pages"><?php echo $this->_data->pagin; ?></div>
</div>
<?php endif; endif; ?>