<?php

//Disable direct view.
if (!defined('IN_PLUGIN'))
    die('You can not access this file directly.');

?>
<ul>
    <li>
        <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
            'action' => 'list'
        ))); ?>" class="tqeLink">List contacts</a>
    </li>
    <li>
        <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
            'action' => 'add'
        ))); ?>" class="tqeLink">Add contact</a>
    </li>
    <li>
        <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
            'action' => 'listCat'
        ))); ?>" class="tqeLink">List categories</a>
    </li>
    <li>
        <a href="<?php echo Tqe_Helpers::makeUrl(AJAX_URL, array_merge($this->_data->urlArgs, array(
            'action' => 'addCat'
        ))); ?>" class="tqeLink">Add category</a>
    </li>
</ul>